name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  # CAMBIA ESTO EN CADA REPO:
  IMAGE_NAME: tu-usuario/ms-products # (o tu-usuario/api-gateway)
  DEPLOYMENT_NAME: ms-products       # (o api-gateway)
  NAMESPACE: app-demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Bajar código
      - uses: actions/checkout@v3

      # 2. Login DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Construir Imagen
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      # 4. (Opcional) Smoke Test Básico
      # Verifica solo si la imagen existe. No corremos curl porque falta la DB.
      - name: Verify Image Build
        run: docker images | grep $IMAGE_NAME

      # 5. Push a DockerHub
      - name: Push Docker Image
        run: |
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      # 6. Desplegar en VPS 1 (Master) via SSH
      # Solo se ejecuta si el Push fue exitoso
      - name: Deploy to K8s via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Forzamos a K8s a actualizar la imagen
            kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=$IMAGE_NAME:${{ github.sha }} -n ${{ env.NAMESPACE }}
            # Verificamos que el rollout sea exitoso
            kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
